# Generated by Django 4.2.1 on 2023-06-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20230527_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('number', models.CharField(blank=True, max_length=128, null=True)),
                ('date_document', models.DateField(blank=True, null=True)),
                ('date_send', models.DateField()),
                ('doc', models.FileField(null=True, upload_to='files/')),
                ('doc_sing', models.FileField(null=True, upload_to='files/')),
                ('status', models.CharField(max_length=15)),
                ('inboxer', models.CharField(max_length=100)),
            ],
        ),
    ]
