# Generated by Django 4.2.1 on 2023-06-27 00:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='recording_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='documents',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
