# Generated by Django 4.2.1 on 2023-06-27 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documents_recording_date_alter_documents_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='doc_sing',
        ),
        migrations.AddField(
            model_name='documents',
            name='doc_sign',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='date_send',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='documents',
            name='inboxer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
