# Generated by Django 4.2.1 on 2023-06-28 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0006_alter_documents_doc_alter_documents_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='documentToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='inbox_documents',
        ),
        migrations.DeleteModel(
            name='send_documents',
        ),
        migrations.AddField(
            model_name='documents',
            name='sender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documenttouser',
            name='id_document',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.documents'),
        ),
        migrations.AddField(
            model_name='documenttouser',
            name='id_inboxer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inboxer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documenttouser',
            name='id_sender',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
