# Generated by Django 4.2.1 on 2023-06-29 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0007_documenttouser_delete_inbox_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='inboxer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inboxer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documents',
            name='sender',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='documentToUser',
        ),
    ]
