# Generated by Django 4.2.1 on 2023-07-14 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0008_alter_documents_inboxer_alter_documents_sender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='usersCerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('containerName', models.CharField(blank=True, max_length=512, null=True)),
                ('owner', models.CharField(blank=True, max_length=512, null=True)),
                ('issuerName', models.CharField(blank=True, max_length=512, null=True)),
                ('serialNumber', models.CharField(blank=True, max_length=512, null=True)),
                ('validFromDate', models.CharField(blank=True, max_length=512, null=True)),
                ('validToDate', models.CharField(blank=True, max_length=512, null=True)),
                ('recording_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
